version: '3.8'
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - '4566:4566'
      - '4571:4571'
    environment:
      - SERVICES=dynamodb,sqs,lambda,cloudwatch,iam
      - LAMBDA_EXECUTOR=docker-reuse
      - EDGE_PORT=4566
      - AWS_DEFAULT_REGION=us-east-1
      - DEBUG=1
    volumes:
      - './localstack:/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
